site_name: "LemonUI"

theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
    accent: blue
  logo: logo.png
  favicon: logo.png
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.prune
    - navigation.top
    - search.suggest
    - search.share

plugins:
  - search
  - mkdoxy:
      projects:
        LemonUI:
          src-dirs: repos/LemonUI/LemonUI
          full-doc: true
          doxy-cfg:
            FILE_PATTERNS: "*.cs"
