name: Update Submodules
on:
  schedule:
    - cron: "12 3 * * *"
  workflow_dispatch:

jobs: 
  update:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          submodules: true
      - run: git submodule update --remote
      - run: git config --global user.name "GitHub Actions" && git config --global user.email "actions@github.com"
      - run: git add * && git commit -m "Updated Submodule Revisions" && git push
 